name: CI Lint and Test

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Shellcheck
        uses: ludeeus/action-shellcheck@master

      - name: Install Bats
        run: |
          sudo apt-get update
          sudo apt-get install -y bats

      - name: Run BATS tests
        uses: bats-core/bats-action@v3
